### ISSUE TITLE
Issue with ".format" and number restriction

### ISSUE THREAD

**Issue by david-unergie** [hapijs/joi-date#14]
#### Context

* *node version*: v6.9.2
* *joi version*: v10.6.0 / v11.4.0 / v12.0.0 / v13.7.0 / v14.3.0
* *environment* (node, browser): node
* *used with* (hapi, standalone, ...): standalone
* *any other relevant information*: joi-date-extensions v1.2.0

#### What are you trying to achieve or the steps to reproduce ?
`joi.date()` accepts a valid date string or a number of milliseconds.
Using `.format()` should accept a valid date string, and should reject number in this case.

Working with joi v9.2.0:
```js
const joi = require('joi')
joi.date().format('YYYY-MM-DD').raw().validate(12)
// => error "value" must be a string with one of the following formats YYYY-MM-DD
```

Failing with v10.6.0 / v11.4.0 / v12.0.0 / v13.7.0 / v14.3.0:
```js
const joi = require('joi').extend(require('joi-date-extensions'))
joi.date().format('YYYY-MM-DD').raw().validate(12)
// => no error, return Number(12)
```

#### Which result you had ?
A number

#### What did you expect ?
An error: "value" must be a string with one of the following formats [YYYY-MM-DD]

**Comment by hueniverse** [comment]
`format()` only applies to strings. I would argue the old behavior was incorrect.

**Comment by david-unergie** [comment]
In this case @hueniverse, how to implement a "joi.date()" in order to allow string only?

**Comment by hueniverse** [comment]
Use `Joi.string()` with a regex pattern. There is no option to not allow numbers as input.

**Comment by david-unergie** [comment]
But in this case, there is no validation about the date consistency. For example, "2019-13-48" will be accepted…

**Comment by hueniverse** [comment]
Like I said, this is not a supported use case. In v16 you can write a custom function validator that checks `helpers.original` to be a string.

**Comment by david-unergie** [comment]
Ok. I just wanted to point out that the old behaviour may not be so bad. Thanks.

**Comment by shadrech** [comment]
I concur with @david-unergie
