### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by codeandcats** [hapijs/joi-date#20]
Test have been failing for 3 or more months now.

<img width="639" alt="Screen Shot 2019-07-17 at 12 16 36 pm" src="https://user-images.githubusercontent.com/6035934/61342291-0e94d200-a88d-11e9-9695-acbd53d41c51.png">

<img width="637" alt="Screen Shot 2019-07-17 at 12 16 51 pm" src="https://user-images.githubusercontent.com/6035934/61342293-118fc280-a88d-11e9-9a56-eba68280b06c.png">

Interestingly the [Joi documentation on extensions](https://github.com/hapijs/joi/blob/v16.0.0-rc2/API.md#extension) doesn't mention the `language` key anymore (though [it used to](https://github.com/hapijs/joi/blob/73f3efdfd9f0ce2dd2c1f83fe7a69e2ee8730aa8/API.md)). Judging by the documentation and the [schema used to validate extensions](https://github.com/hapijs/joi/blob/55b885ee2c8ecee3c0e568dccc547ad74dfe2a0c/lib/schemas.js#L51), it seems to have been renamed to `messages`. However, simply changing `language` to `messages` in the joi-date extension breaks the tests in a far noisier way. 😬I'm not sure what the problem is exactly.

**Comment by Marsup** [comment]
There was indeed a change with the options in joi 15. I'll see about joi 16 support later. Thanks for the report.
