### ISSUE TITLE
Cannot use @hapi/joi-date

### ISSUE THREAD

**Issue by EagleHawk** [hapijs/joi-date#21]
I am not able to use the libary in node.js.
After installing 
`npm install @hapi/joi-date --save`

And after importing 
`const hapiJoiExt = require('@hapi/joi-date');`

it says 

> module "c:/Users/userdir/rx-developer/project_feat_branches/project/node_modules/@hapi/joi-date/lib/index"
> Could not find a declaration file for module '@hapi/joi-date'. 'c:/Users/userdir/rx-developer/project_feat_branches/project/node_modules/@hapi/joi-date/lib/index.js' implicitly has an 'any' type.
>   Try `npm install @types/hapi__joi-date` if it exists or add a new declaration (.d.ts) file containing `declare module '@hapi/joi-date';`ts(7016)
> 

but there is no @types/hapi__joi-date.

Please provide a resolution for this.

**Comment by WesTyler** [comment]
There's a big difference between "I cannot use this, fix it" and "I expect every dependency I use to support TypeScript and provide me with type definitions"...
