### ISSUE TITLE
I'm not able to install the v2.1.0 version

### ISSUE THREAD

**Issue by wujekbogdan** [hapijs/joi-date#44]
#### Support plan

* *is this issue currently blocking your project?* (no):
* *is this issue affecting a production system?* (no):

#### Context

* *node version*: any
* *module version*: 2.1.0
* *environment* : any
* *used with*: irrelevant

#### How can we help?

I can install the `2.1.0` version only by pointing to a git commit:

``` json
{
  "@joi/date": "hapijs/joi-date#c00242986be6af9577bd449b64192e2f512bedf9",
}
```

Or to a git tag:

``` json
{
  "@joi/date": "hapijs/joi-date#v2.1.0",
}
```

But If I specify the `2.1.0` version:

```json
{
  "@hapi/joi-date": "2.1.0",
}
```

then I'm getting the following message:

<img width="573" alt="Zrzut ekranu 2023-02-22 o 12 27 11" src="https://user-images.githubusercontent.com/533954/220607686-ee4a6e6a-2bef-4369-a0d0-11695c80f8e1.png">

It seems that the `2.1.0` version wasn't pushed to the NPM registry.

**Comment by kanongil** [comment]
Thanks for reporting. With v2.1.0 it was moved to the `@joi/date` npm repo.

AFAIK, it has since then been moved back to the hapijs org, but I guess no one has published the new version against this, so it is still at v2.0.1.

**Comment by Marsup** [comment]
I'm not sure I understand why you didn't simply try `"@joi/date": "2.1.0"`.
